export const plans = [
  {
    id: 1,
    name: "Free",
    price: 0,
    payType: "Pay Once",
    priceId: "pri_01h9mghe4gbtqc0s7e25dch51g",
    specifications: [
      "3000 views per month",
      "1 website",
      "Has ‘Made with SlideBites’ badge",
      "Import Twitter threads, LinkedIn posts & Facebook posts",
    ],
    views: 3000,
    websites: 1,
    badgeShow: true,
    AIAssistance: false,
    upcomingFeatures: false,
  },
  {
    id: 2,
    name: "Starter",
    price: 49,
    payType: "Pay Once",
    priceId: "pri_01h9mgk8bqqy4naybp0wsaqcff",
    specifications: [
      " 6,000 views per month",
      "1 website",
      "Import Twitter threads, LinkedIn posts & Facebook posts",
      "AI assistant",
      "All upcoming features",
    ],
    views: 6000,
    websites: 1,
    badgeShow: false,
    AIAssistance: true,
    upcomingFeatures: true,
  },
  {
    id: 3,
    name: "Pro",
    price: 89,
    payType: "Pay Once",
    priceId: "pri_01h9mgnqvbdw67nengb0zmtrb5",
    specifications: [
      "16,000 views per month",
      "5 website",
      "Import Twitter threads, LinkedIn posts & Facebook posts",
      "AI assistant",
      "All upcoming features",
    ],
    views: 16000,
    websites: 5,
    badgeShow: false,
    AIAssistance: true,
    upcomingFeatures: true,
  },
  {
    id: 4,
    name: "Ultimate",
    price: 149,
    payType: "Pay Once",
    priceId: "pri_01hb3zv6snaeaqrkx5evnrdxpe",
    specifications: [
      "50,000 views per month",
      "25 website",
      "Import Twitter threads, LinkedIn posts & Facebook posts",
      "AI assistant",
      "All upcoming features",
    ],
    views: 50000,
    websites: 25,
    badgeShow: false,
    AIAssistance: true,
    upcomingFeatures: true,
  },
];
