export const adminEmails = [
  "myrcgeeks@gmail.com",
  "ukhalid639@gmail.com",
  "shahjahan@teamants.com",
];

export const plans = [
  {
    id: 1,
    name: "Free",
    price: 0,
    payType: "Pay Once",
    priceId: "pri_01h9mghe4gbtqc0s7e25dch51g",
    specifications: [
      "1000 views per month",
      "1 website",
      "Has ‘Made with Typedd badge",
      "Import Twitter threads, LinkedIn posts & Facebook posts",
    ],
    views: 1000,
    websites: 1,
    badgeShow: true,
    AIAssistance: false,
    upcomingFeatures: false,
  },
  {
    id: 2,
    name: "Starter",
    price: 49,
    payType: "Pay Once",
    priceId: "pri_01hcvntcdtphhs8qvgbs618cfv",
    specifications: [
      "6,000 views per month",
      "1 website",
      "Import Twitter threads, LinkedIn posts & Facebook posts",
      "AI assistant",
      "All upcoming features",
    ],
    views: 6000,
    websites: 1,
    badgeShow: false,
    AIAssistance: true,
    upcomingFeatures: true,
  },
  {
    id: 3,
    name: "Pro",
    price: 89,
    payType: "Pay Once",
    priceId: "pri_01hcvny257xq273v0504b4nkc2",
    specifications: [
      "10,000 views per month",
      "5 websites",
      "Import Twitter threads, LinkedIn posts & Facebook posts",
      "AI assistantance",
      "All upcoming features",
    ],
    views: 16000,
    websites: 5,
    badgeShow: false,
    AIAssistance: true,
    upcomingFeatures: true,
  },
  {
    id: 4,
    name: "Agency",
    price: 149,
    payType: "Pay Once",
    priceId: "pri_01hcvnzh8a62f0a3j1n8h2mmd9",
    specifications: [
      "50,000 views per month",
      "25 websites",
      "Import Twitter threads, LinkedIn posts & Facebook posts",
      "AI assistant",
      "All upcoming features",
    ],
    views: 50000,
    websites: 25,
    badgeShow: false,
    AIAssistance: true,
    upcomingFeatures: true,
  },
];
