export const plans = [
  {
    id: 1,
    name: "Free",
    price: 0,
    payType: "Pay Once",
    priceId: "pri_01h9mghe4gbtqc0s7e25dch51g",
    specifications: [
      "500 views per month",
      "1 website",
      "Has ‘Made with SlideBites’ badge",
      "Import Twitter threads, LinkedIn posts & Facebook posts",
    ],
    views: 500,
    websites: 1,
    badgeShow: true,
    AIAssistance: false,
    upcomingFeatures: false,
  },
  {
    id: 2,
    name: "Silver",
    price: 75,
    payType: "Pay Once",
    priceId: "pri_01h9mgk8bqqy4naybp0wsaqcff",
    specifications: [
      "5000 views per month",
      "1 website",
      "Import Twitter threads, LinkedIn posts & Facebook posts",
      "AI assistant",
      "All upcoming features",
    ],
    views: 5000,
    websites: 1,
    badgeShow: false,
    AIAssistance: true,
    upcomingFeatures: true,
  },
  {
    id: 3,
    name: "Gold",
    price: 149,
    payType: "Pay Once",
    priceId: "pri_01h9mgnqvbdw67nengb0zmtrb5",
    specifications: [
      "Unlimited views per month",
      "10 website",
      "Import Twitter threads, LinkedIn posts & Facebook posts",
      "AI assistant",
      "All upcoming features",
    ],
    views: 99999999,
    websites: 10,
    badgeShow: false,
    AIAssistance: true,
    upcomingFeatures: true,
  },
];
